### ISSUE TITLE
Assertion in ref_counted::add_ref()

### ISSUE THREAD

**Issue by gavv** [gershnik/intrusive_shared_ptr#1]
Hi, thanks for sharing this library!

In ref_counted::add_ref(), there is an assertion that `oldcount` was non-zero:

https://github.com/gershnik/intrusive_shared_ptr/blob/dc36ce29308320349146cb946c46c26dfb0b2cfa/inc/intrusive_shared_ptr/ref_counted.h#L423

I understand the reason for it, but it prevented me from using ref_counted in my use-case. I solved this problem by implementing my own reference counter and using isptr::intrusive_shared_ptr with custom traits. However I'll still describe my use-case, so that you can consider changing this assertion.

The use-case:

* I have a pool of objects
* Objects in pool have reference counter to zero
* When user acquires object from pool, it finds object, increments ref counter, and returns intrusive_shared_ptr
* When ref counter of returned object reaches zero, object is returned back to pool

The assertion mentioned above fails when add_ref() is called for an object that was "released" to pool. This assertion assumes that the object is never used after its counter reaches zero, but in case of pool that's not true.

**Comment by gershnik** [comment]
Hi! Thank you for the interest and the suggestion!

There are multiple things at play here. To begin with the assert you mention is a symptom, not the cause of the problem you experience. The `ref_counted` class has one strong invariant: "live objects have refcount > 0". Trying to violate it will break many, many things so the way you were attempting to use it won't work even if assert were removed. The assert is just there to verify the invariant and overall sanity. You can see the reason for the invariant in [this doc](https://github.com/gershnik/intrusive_shared_ptr/blob/master/doc/reference_counting.md).

Now, your overall goal, if I understand it correctly, is basically to have refcounted objects that live two separate lives. In one life (inside cache) the object is a regular single-owner C++ object. It is created and destroyed by its owner. In another life (when given out) it is shared among multiple owners. When its usage count drops to 0 this life ends and it resumes its original one. 

In this scenario `ref_counted` as is won't work - it only has a single life. Multiple solutions are possible depending on desired complexity and other trade-offs. 
One "clever" way to do so is to "say what you mean" and literally create `ref_counted` part of your object when giving it away. Something like this (warning untested code typed directly here):

```cpp
struct foo : ref_counted<foo> {
    void destroy() {
        //return back to cache (I assume you already had this)
    }
};

auto cache::get_foo() -> refcnt_ptr<foo> {

    foo * obj = ...obtain needed object ...
    auto subobject = static_cast<ref_counted<foo> *>(obj);
    //destroy the original subobject to avoid undefined behavior(should optimize to no-op)
    subobject->~ref_counted<foo>();
    //create new one (this is noexcept)
    new (subobject) ref_counted<foo>();
    return refcnt_attach(obj);
}

```

Hope it helps!

**Comment by gavv** [comment]
Thanks! From the linked article the rationale is now clear.

> One "clever" way to do so is to "say what you mean" and literally create ref_counted part of your object when giving it away.

Nice trick. Thought, in my specific case, implementing custom add_ref() and sub_ref() should be safe (I control when destructors are called and when they do) and is much simpler to understand :)

**Comment by gershnik** [comment]
Absolutely! It all comes down to desired complexity, extensibility and other trade-offs. For a simple case, indeed, just having your own custom add_ref/sub_ref semantics is likely the easiest solution. On the other hand, just to give a random example, if you later decide you need weak pointers the trade-offs might change.
The goal of this library is to be modular and customizable to let the user be able to pick the pieces that work best for each specific scenario with 0 overhead. I am glad it seems to accomplish this in your case.

Thank you!
